# -*- coding: utf-8 -*-
"""config.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uessc9KYGh9Hiko-s9TzVRQQ_dRy7rQd
"""

import os

PDF_PATH = "data/knowledge.pdf"
CHROMA_PATH = "chroma_db"

CHUNK_SIZE = 800
CHUNK_OVERLAP = 150
TOP_K = 3
CONFIDENCE_THRESHOLD = 0.6